### ISSUE TITLE
[BUG] varSel not working after model train

### ISSUE THREAD

**Issue by Rogerio-7** [ConsBiol-unibern/SDMtune#15]
Hi, I'm trying to follow the package's workflow, but the same error always occurs in the varSel step. 

set.seed(0)
bg_full <- randomPoints(MEX_pred, n = 10000, onca_full, ext= MEX_pred, extf=1, excludep=TRUE, prob=FALSE, 
                        cellnumbers=FALSE, tryf=3, warn=2, lonlatCorrection=TRUE)

onca_full <- data.frame(onca_full)
bg_full<-data.frame(bg_full)

data_full<- prepareSWD(species = "Panthera_onca", p = onca_full , a = bg_full,
                       env = MEX_pred)

#Spatialblocks
sac <- spatialAutoRange(rasterLayer = MEX_pred,
                        sampleNumber = 5000,
                        doParallel = TRUE,
                        showPlots = TRUE)

e_folds_full <- spatialBlock(speciesData = sp_df_full,
                             rasterLayer = MEX_pred,
                             theRange = 403023,
                             selection = "random",
                             iteration = 100, # find evenly dispersed folds
                             biomod2Format = FALSE,
                             xOffset = 0, # shift the blocks horizontally
                             yOffset = 0)

#Model
cv_model_full <- train(method = "Maxent", data = data_full, folds = e_folds_full, iter = 700)

#varSel

bg_var_sel <- prepareSWD(species = "Panthera onca", a = bg_full, env = MEX_pred)

plotCor(bg_var_sel, method = "spearman", cor_th = 0.7)

corVar(bg_var_sel, method = "spearman", cor_th = 0.7)

vs <- varSel(cv_model_full, metric = "auc", test = NULL,
                                   bg4cor = bg_var_sel, method = "spearman",
                                   cor_th = 0.7, permut = 10)

After some time i get this error :

Error in `[<-.data.frame`(`*tmp*`, variables[i], value = NULL) : 
  missing values are not allowed in subscripted assignments of data frames

![error_bug](https://user-images.githubusercontent.com/90930770/133838846-a6062fcb-5d68-4297-bb1c-74e41bd6a7d6.PNG)

**Comment by sgvignali** [comment]
Hi, thank you for reporting the problem. Could you please provide a reproducible example using the data included in the package?

**Comment by Rogerio-7** [comment]
**Hi, using the data included in the package the process runs properly:**

library(SDMtune)
library(ggplot2)    # To plot locations
library(maps)       # To access useful maps
library(rasterVis)  # To plot raster objects
library(blockCV)

files <- list.files(path = file.path(system.file(package = "dismo"), "ex"),
                    pattern = "grd", full.names = TRUE)

predictors <- raster::stack(files)
names(predictors)


help(virtualSp)
p_coords <- virtualSp$presence
bg_coords <- virtualSp$background

ggplot(map_data("world"), aes(long, lat)) +
  geom_polygon(aes(group = group), fill = "grey95", color = "gray40", size = 0.2) +
  geom_jitter(data = p_coords, aes(x = x, y = y), color = "red",
              alpha = 0.4, size = 1) +
  labs(x = "longitude", y = "latitude") +
  theme_minimal() +
  theme(legend.position = "none") +
  coord_fixed() +
  scale_x_continuous(limits = c(-125, -32)) +
  scale_y_continuous(limits = c(-56, 40))

p_coords <- data.frame(p_coords)
bg_coords<-data.frame(bg_coords)

data <- prepareSWD(species = "Virtual species", p = p_coords, a = bg_coords,
                   env = predictors, categorical = "biome")


sp_df_full <- SpatialPointsDataFrame(data@coords,
                                     data = as.data.frame(data@pa),
                                     proj4string = crs(predictors))


#blockCV
sac <- spatialAutoRange(rasterLayer = predictors,
                        sampleNumber = 5000,
                        doParallel = TRUE,
                        showPlots = TRUE)

#Spatial blocks
e_folds_full <- spatialBlock(speciesData = sp_df_full,
                             rasterLayer = predictors,
                             theRange = 180386, 
                             selection = "random",
                             iteration = 100, # find evenly dispersed folds
                             biomod2Format = FALSE,
                             xOffset = 0, # shift the blocks horizontally
                             yOffset = 0)


model <- train(method = "Maxent", data = data, folds = e_folds_full, iter = 700)


bg_var_sel <- prepareSWD(species = "Panthera onca", a = bg_coords, env = predictors, categorical = "biome")

plotCor(bg_var_sel, method = "spearman", cor_th = 0.7)

corVar(bg_var_sel, method = "spearman", cor_th = 0.7)

vs <- varSel(model, metric = "auc", test = NULL,
             bg4cor = bg_var_sel, method = "spearman",
             cor_th = 0.7, permut = 10)


**About the error with my data:** 

I do not understand this error: _Error in [<-.data.frame(*tmp*, variables[i], value = NULL) :
missing values are not allowed in subscripted assignments of data frames_, because my .csv do not have any NA values.

**Comment by sgvignali** [comment]
Difficult to say if I cannot reproduce the error... the error doesn't refer to NA values in your dataset, these are anyway removed by the `prepareSWD()` function.
It looks like a mismatch between the variables used to train the model and the ones included in the background locations used to check for high correlation, but again, I cannot say without reproducing the problem

**Comment by peterpothmann** [comment]
I am experiencing the same error described here. From my analysis, it seems to occur when a large number of predictor raster values are 0. Could this be the cause? Here is a reproducible example:

```
library(geodata)
library(terra)
library(flexsdm)
library(tibble)
library(sf)

# get predictor data
tmin <- worldclim_country("germany", var=c("tmin"), path=tempdir())
tmax <- worldclim_country("germany", var=c("tmax"), path=tempdir())
e <- elevation_30s("germany", path=tempdir())
e <- ifel(e < 2000, 0, e) # set most of the pixel values to 0
e <- resample(e, tmax)

# combine
predictor <- c(tmin, tmax) # with this set it works
predictorError <- c(tmin, tmax, e) # this does not work

# get occurrence data
set.seed(1)
occ <- spatSample(x = predictor, size = 1000, as.points = TRUE, values = FALSE)

occ <- occ |> 
  st_as_sf() |> 
  st_coordinates() |> 
  as_tibble() |> 
  rowid_to_column() 

# create bg points
bg <- sample_background(
  data = occ,
  x = "X",
  y = "Y",
  n = 2000,
  method = "random",
  rlayer = predictor[[1]],
)

modelData <- prepareSWD(species = "Aedes vexans",
                        p = occ |> select(X, Y),
                        a = bg |> select (X,Y),
                        env = predictor)

# create folds
folds <- randomFolds(modelData,
                     k = 4,
                     only_presence = TRUE,
                     seed = 1)

# train the model
meModel <- train(method = "Maxent",
                 data = modelData,
                 fc = "l", 
                 reg = 0.8,
                 folds = folds)

bgVarSel<- prepareSWD(species = "Aedes vexans",
                 a = bg |> select (X,Y),
                 env = predictorError) # predictor works - predictorError fails 

meModel <- varSel(meModel, 
                  metric = "auc", 
                  bg4cor = bgVarSel, 
                  method = "spearman", 
                  cor_th = 0.7, 
                  permut = 1)

# This is the error message I recieve when preparing the bg with env = predictorError
# Error in `[<-.data.frame`(`*tmp*`, variables[i], value = NULL) : 
#   missing values are not allowed in subscripted assignments of data frames
# In addition: Warning messages:
#   1: In stats::cor(df, method = method) : the standard deviation is zero
# 2: In stats::cor(df, method = method) : the standard deviation is zero
```

### SessionInfo

```
R version 4.3.3 (2024-02-29 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8    LC_MONETARY=German_Germany.utf8
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.utf8    

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] geodata_0.5-9   SDMtune_1.3.1   flexsdm_1.3.4   sf_1.0-16       terra_1.7-78    readxl_1.4.3   
 [7] lubridate_1.9.3 forcats_1.0.0   stringr_1.5.1   dplyr_1.1.4     purrr_1.0.2     readr_2.1.5    
[13] tidyr_1.3.1     tibble_3.2.1    ggplot2_3.5.0   tidyverse_2.0.0

loaded via a namespace (and not attached):
 [1] tidyselect_1.2.1     viridisLite_0.4.2    fields_15.2          dotCall64_1.1-1     
 [5] timechange_0.3.0     lifecycle_1.0.4      survival_3.5-8       magrittr_2.0.3      
 [9] kernlab_0.9-32       compiler_4.3.3       rlang_1.1.3          tools_4.3.3         
[13] utf8_1.2.4           knitr_1.47           sp_2.1-3             classInt_0.4-10     
[17] plyr_1.8.9           KernSmooth_2.23-22   withr_3.0.0          nnet_7.3-19         
[21] grid_4.3.3           fansi_1.0.6          e1071_1.7-14         colorspace_2.1-0    
[25] scales_1.3.0         iterators_1.0.14     cli_3.6.2            generics_0.1.3      
[29] rstudioapi_0.16.0    reshape2_1.4.4       tzdb_0.4.0           DBI_1.2.2           
[33] proxy_0.4-27         splines_4.3.3        maps_3.4.2           parallel_4.3.3      
[37] cellranger_1.1.0     vctrs_0.6.5          Matrix_1.6-5         jsonlite_1.8.8      
[41] hms_1.1.3            patchwork_1.2.0.9000 spThin_0.2.0         foreach_1.5.2       
[45] units_0.8-5          glue_1.7.0           spam_2.10-0          codetools_0.2-20    
[49] dismo_1.3-14         stringi_1.8.3        rJava_1.0-11         gtable_0.3.5        
[53] raster_3.6-26        munsell_0.5.1        pillar_1.9.0         randomForest_4.7-1.1
[57] gbm_2.1.9            R6_2.5.1             doParallel_1.0.17    maxnet_0.1.4        
[61] lattice_0.22-6       class_7.3-22         Rcpp_1.0.12          nlme_3.1-164        
[65] mgcv_1.9-1           whisker_0.4.1        xfun_0.45            pkgconfig_2.0.3   
```

If you need any additional information, please let me know. I would greatly appreciate any assistance!
