### ISSUE TITLE
Disable real-time graph???

### ISSUE THREAD

**Issue by Hallo951** [ConsBiol-unibern/SDMtune#16]
Hello, 
is there any way to turn off the realtime graph globally or partially? I want to run different functions from their package in a parallel foreach loop. This works very well, however for each individual instance of the parallel foreach loop it opens a separate window in the browser (firefox) in which it displays and updates the corresponding realtime graph. I would like to stop this behavior. Is there a simple way?

Thanks.
best regards Frank

**Comment by sgvignali** [comment]
Hi Frank,
at the moment is not possible to deactivate the real-time charts.
I can implement it but I cannot say when, at the moment I'm very busy.

**Comment by sgvignali** [comment]
Hi @Hallo951, this has been now implemented. All functions with a real-time interactive chart gained the new argument `interactive` to disable the chart.
