### ISSUE TITLE
[Feature request]: convert SDMmodelCV to SDMmodel

### ISSUE THREAD

**Issue by ptitle** [ConsBiol-unibern/SDMtune#26]
### Describe the new feature

It's very convenient that we can pass spatial folds to the model training and get a `SDMmodelCV` object, which a number of functions take as input. However, a number of other functions do not accept `SDMmodelCV` objects. Would be helpful to have a function that "collapses" a `SDMmodelCV` object to a `SDMmodel` object, which would mean lumping all of the occurrences and backgrounds and retraining the model with the parameters found in the `SDMmodelCV` object. As far as I can tell, this does not currently exist. Just a suggestion.

### Does the feature request already exist?

- [X] I have check if the same feature request already exists

**Comment by sgvignali** [comment]
I could implement it, any idea on how to name this function?

**Comment by ptitle** [comment]
Perhaps collapseSDMmodelCV? Or combineSDMmodelCV?

**Comment by sgvignali** [comment]
The function [`combineCV()`](https://consbiol-unibern.github.io/SDMtune/dev/reference/combineCV.html) is implemented. I will release the new version of the package in the coming days but if you want to test the function you can install the development version. I'm also updating the website.

**Comment by ptitle** [comment]
Seems to work -- thanks!
