### ISSUE TITLE
[Feature request]: have plotResponse invisibly return the data

### ISSUE THREAD

**Issue by ptitle** [ConsBiol-unibern/SDMtune#27]
### Describe the new feature

Currently, `plotResponse()` will generate a ggplot-based plot. But if I would like to generate my own figures, it would be helpful if the function invisibly returned the data used to generate the plot (and by invisibly, I mean that if you assigned to a variable, the data would be passed to that variable, but it would not print the data to the console if not assigned. See `base::invisible()`). 

### Does the feature request already exist?

- [X] I have check if the same feature request already exists

**Comment by sgvignali** [comment]
The function `plotResponse` returns the `ggplot` object. If you want to modify the plot, first you have to assign the function output to a variable, and then you two options:

1. Modify the `ggplot` object by editing the theme or adding additional elements
2. Get the data with `ggplot2::ggplot_build()` and build your own plot

If you go for the second option, you could do something like that:

```r
my_plot <- plotResponse(my_model,
                        var = "my_var")
data <- ggplot2::ggplot_build(my_plot)$data
```

I hope this helps!

**Comment by ptitle** [comment]
That does help -- Thanks! Perhaps including this in the documentation for the function would be helpful to others facing a similar use case.

**Comment by sgvignali** [comment]
Please, notice that all the `plot` functions return a `ggplot` object.

In the documentation you can read that the function returns a `ggplot` object. The rest is about modifying a `ggplot` object and goes beyond the scope of the package.

**Comment by ptitle** [comment]
Fair enough.

**Comment by sgvignali** [comment]
I added and example in the function documentation, have a look at it: https://consbiol-unibern.github.io/SDMtune/reference/plotResponse.html
