### ISSUE TITLE
Customizing response curves

### ISSUE THREAD

**Issue by yucheols** [ConsBiol-unibern/SDMtune#28]
### Describe the new feature

Hello!
I've been using SDMtune for some time now and I really enjoy using it. This is a great tool to run SDMs. So first of all, thank you for this great package!

This is more of a question than a feature request (sorry for putting it here, but this seemed more appropriate than the bug report).
I'm working on SDMs of two amphibian species and was thinking about plotting the responses of the two species within a single plotting pane (for each variable). But since the "plotResponse" function returns one plot for one species and one variabe at a time I was wondering if there's a way to "pull out" data for response curves so that the response plots can be customized (e.g. in ggplot)?

Thank you in advance for the help!
Cheers,
Yucheol 

### Does the feature request already exist?

- [X] I have check if the same feature request already exists

**Comment by sgvignali** [comment]
I have a look at the examples provided in the `plotResponse()` function: https://consbiol-unibern.github.io/SDMtune/reference/plotResponse.html. There is explained how to extract the data form the output of the function. Is this what you need?

**Comment by sgvignali** [comment]
I think I can close this issue @yucheols, right?
