### ISSUE TITLE
Error in `optimizeModel` when passing a SDMmodelCV object

### ISSUE THREAD

**Issue by veroandreo** [ConsBiol-unibern/SDMtune#3]
Hello, 

I'm following the workflow in https://consbiol-unibern.github.io/SDMtune/articles/articles/tune_hyperparameters.html by adapting it to a particular case for modeling occurrence of a disease. These are the commands I've used:

```
# train a maxnet model with CV (presences are very few as to split the dataset)
model <- train("Maxnet", p = presence, a = bg_model, 
               fc = "lh", reg = 0.5, seed = 37, rep = 3)

# reduce number of vars in the model according to importance
reduced_var_model <- reduceVar(model, th = 9, metric = "auc", test = TRUE, 
                                     permut = 1, use_jk = TRUE)

# optimize model with genetic algorithm
h <- list(a = seq(4000, 9000, 500), reg = seq(0.2, 5, 0.2), fc = c("l", "lq", "lh", "lp", "lqp", "lqph"))
opt_model <- optimizeModel(reduced_var_model, 
                            hypers = h, 
                            metric = "auc", 
                            bg4test = bg, 
                            pop = 20, 
                            gen = 5, 
                            keep_best = 0.4, 
                            keep_random = 0.2, 
                            mutation_chance = 0.4, 
                            seed = 65651)
```
So far so good, until the optimization step that I get:

```
Cross Validation [========================] 100% in 00:00:22
[...]
Cross Validation [========================] 100% in 00:00:12
Optimize Model [=========================>]  98% in 00:06:09
Error in .create_sdmtune_output(models, metric, train_metric, val_metric) : 
  no slot of name "model" for this object of class "SDMmodelCV"
```

However, the `optimizeModel` function is supposed to accept objects of type `SDMmodelCV` according to the manual page. What could be the problem?

**Comment by sgvignali** [comment]
Hi,
could you try the same code using Maxent instead of Maxnet? Sometimes I couldn't run Maxnet models for certain combinations of fc and reg, and that might be the case.

**Comment by veroandreo** [comment]
I just tried the same code with MaxEnt, but with no success. I get the same error. Any other hint?

**Comment by sgvignali** [comment]
I cannot reproduce your error. Which version of R are you using? Could you please print the reduce_var_model object? I tried your code with the condor dataset but I didn't get any error.
Could you try as well with the condor dataset?

**Comment by veroandreo** [comment]
I ran it with condor data set now following the tutorial, but with a CV model (as in my use case) and I always get the same error as reported. Is this related to R version?

```
# env vars
files <- list.files(path = paste(system.file(package = "dismo"), "/ex", sep = ""), pattern = "grd", full.names = TRUE)
predictors <- stack(files)

# presences
p_coords <- condor[, 1:2]

# bg
set.seed(49)
bg_coords <- dismo::randomPoints(predictors, 10000)

# SWD
presence <- prepareSWD(species = "Vultur gryphus", coords = p_coords, env = predictors, categorical = "biome")
bg <- prepareSWD(species = "Vultur gryphus", coords = bg_coords, env = predictors, categorical = "biome")
bg_model <- getSubsample(bg, 5000, seed = 49)

# train CV model
model <- train("Maxent", p = presence, a = bg_model, fc = "lh", reg = 0.5, seed = 37, rep = 3)

# reduce number of vars in the model according to importance
reduced_var_model <- reduceVar(model, th = 9, metric = "auc", test = TRUE, permut = 1, use_jk = TRUE)

# optimize model with genetic algorithm
h <- list(a = seq(4000, 9000, 500), reg = seq(0.2, 5, 0.2), fc = c("l", "lq", "lh", "lp", "lqp", "lqph"))
opt_model <- optimizeModel(reduced_var_model, 
                           hypers = h, 
                           metric = "auc", 
                           bg4test = bg, 
                           pop = 20, 
                           gen = 5, 
                           keep_best = 0.4, 
                           keep_random = 0.2, 
                           mutation_chance = 0.4, 
                           seed = 65651)
```
The output of `reduced_var_model`

```
Object of class SDMmodelCV 
Method: Maxent 

Species: Vultur gryphus 
Replicates: 3 
Presence locations: 510 

Model configurations:
--------------------
a: 5000
fc: lh
reg: 0.5
iter: 500

Variables:
---------
Continuous: bio1 bio16 bio17 bio5 bio6 bio7 bio8 
Categorical: biome
```

My session info:
```
R version 3.5.3 (2019-03-11)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 29 (Twenty Nine)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8          LC_NUMERIC=C                 
 [3] LC_TIME=en_US.UTF-8           LC_COLLATE=en_US.UTF-8       
 [5] LC_MONETARY=en_US.UTF-8       LC_MESSAGES=en_US.UTF-8      
 [7] LC_PAPER=en_US.UTF-8          LC_NAME=en_US.UTF-8          
 [9] LC_ADDRESS=en_US.UTF-8        LC_TELEPHONE=en_US.UTF-8     
[11] LC_MEASUREMENT=en_US.UTF-8    LC_IDENTIFICATION=en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dplyr_0.8.1         zeallot_0.1.0       SDMtune_0.1.0       rasterVis_0.45     
 [5] latticeExtra_0.6-28 RColorBrewer_1.1-2  lattice_0.20-38     maps_3.3.0         
 [9] biomod2_3.3-7.1     ggplot2_3.1.1       reshape_0.8.8       usdm_1.1-18        
[13] dismo_1.1-4         sf_0.7-4            mapview_2.7.0       rgrass7_0.1-12     
[17] XML_3.98-1.19       raster_2.9-5        sp_1.3-1           

loaded via a namespace (and not attached):
 [1] satellite_1.0.1       webshot_0.5.1         progress_1.2.2       
 [4] tools_3.5.3           rgdal_1.4-4           R6_2.4.0             
 [7] rpart_4.1-13          KernSmooth_2.23-15    DBI_1.0.0            
[10] lazyeval_0.2.2        colorspace_1.4-1      nnet_7.3-12          
[13] withr_2.1.2           maxnet_0.1.2          gbm_2.1.5            
[16] tidyselect_0.2.5      gridExtra_2.3         prettyunits_1.0.2    
[19] leaflet_2.0.2         compiler_3.5.3        mda_0.4-10           
[22] leafem_0.0.1          cli_1.1.0             scales_1.0.0         
[25] classInt_0.3-3        hexbin_1.27.3         randomForest_4.6-14  
[28] plotmo_3.5.4          PresenceAbsence_1.1.9 stringr_1.4.0        
[31] digest_0.6.19         base64enc_0.1-3       pkgconfig_2.0.2      
[34] htmltools_0.3.6       plotrix_3.7-5         htmlwidgets_1.3      
[37] rlang_0.3.4           rstudioapi_0.10       shiny_1.3.2          
[40] zoo_1.8-6             jsonlite_1.6          crosstalk_1.0.0      
[43] magrittr_1.5          Formula_1.2-3         Matrix_1.2-17        
[46] Rcpp_1.0.1            munsell_0.5.0         abind_1.4-5          
[49] yaml_2.2.0            stringi_1.4.3         whisker_0.3-2        
[52] pROC_1.15.0           MASS_7.3-51.4         plyr_1.8.4           
[55] grid_3.5.3            earth_5.1.1           promises_1.0.1       
[58] crayon_1.3.4          splines_3.5.3         hms_0.4.2            
[61] pillar_1.4.1          reshape2_1.4.3        codetools_0.2-16     
[64] stats4_3.5.3          glue_1.3.1            png_0.1-7            
[67] httpuv_1.5.1          gtable_0.3.0          purrr_0.3.2          
[70] assertthat_0.2.1      TeachingDemos_2.10    mime_0.6             
[73] xtable_1.8-4          e1071_1.7-1           later_0.8.0          
[76] class_7.3-15          survival_2.43-3       viridisLite_0.3.0    
[79] tibble_2.1.2          rJava_0.9-11          units_0.6-3          
```

**Comment by sgvignali** [comment]
No, is not R version related, but is very weird.
I tried two different R versions without problem:
```
> opt_model <- optimizeModel(reduced_var_model, 
+                            hypers = h, 
+                            metric = "auc", 
+                            bg4test = bg, 
+                            pop = 20, 
+                            gen = 5, 
+                            keep_best = 0.4, 
+                            keep_random = 0.2, 
+                            mutation_chance = 0.4, 
+                            seed = 65651)
Optimize Model [==========================] 100% in 00:01:57
```

The error seems to occur in the function `.create_sdmtune_output` that get executed at the end of the optimization process in order to create the output. You can see the involved code here: https://github.com/ConsBiol-unibern/SDMtune/blob/master/R/utils.R at line 136:
`res[i, tunable_hypers[j]] <- slot(m@model, tunable_hypers[j])`.

It seems that in your case the `m` variable is an SDMmodelCV object instead of an SDMmodel one. This shouldn't be possible because at line 125-129 there is an if statement to avoid that...

I assume that you get the same error with the function `gridSearch`, right?

I don't know why you get this error and if I cannot reproduce it it's hard for e to find a solution. Just to be sure that the problem is the one I described, could you please run the following code?

```
x <- SDMtune:::.create_sdmtune_output(list(reduced_var_model, reduced_var_model), metric = "auc",
+                                                               train_metric = data.frame(x = c(1, 2), y = c(.8, .9)),
+                                                               val_metric = data.frame(x = c(1, 2), y = c(.6, .8))
                                                                 ) 
```

**Comment by veroandreo** [comment]
I run the piece of code you shared and yes, that triggers the error. I also tested with `gridSearch` and the same error pops up. 

I was checking the code in the lines you mention: https://github.com/ConsBiol-unibern/SDMtune/blob/498bea99ed624eb7a8c3602e4697423a2c0b5e62/R/utils.R#L128 

sorry for my ignorance here, but  why is it ```models[[i]]@models[[1]]``` in line 128? Shouldn't that be ```models@models[[i]]``` for a CV object? And why only model 1 in the CV object will be used?

**Comment by sgvignali** [comment]
`models` in this case is the list of models generated by the `optimizeModel` function, so `models[[i]]` is the ith model in the list. The `.create_sdmtune_output` function loops through these models and create the SDMtune object.

The code is correct. It doesn't matter which model is taken from the SDMmodelCV object, they all have the same value of "reg", "a", "fc" and "iter" (iter only for Maxent models).

Could you please send me the output of the following code?
```
x <- list(reduced_var_model, reduced_var_model)
x[[1]]@models[[1]]
x[[1]]@models[[1]]@model
```

**Comment by veroandreo** [comment]
Thanks for your patience! :)

Here's the output: 
```
x <- list(reduced_var_model, reduced_var_model)
x[[1]]
Object of class SDMmodelCV 
Method: Maxent 

Species: Vultur gryphus 
Replicates: 3 
Presence locations: 510 

Model configurations:
--------------------
a: 5000
fc: lh
reg: 0.5
iter: 500

Variables:
---------
Continuous: bio1 bio16 bio17 bio5 bio6 bio7 bio8 
Categorical: biome

x[[1]]@models[[1]]
Object of class SDMmodel 
Method: Maxent 

Species: Vultur gryphus 
Presence locations: 340 

Model configurations:
--------------------
a: 5000
fc: lh
reg: 0.5
iter: 500

Variables:
---------
Continuous: bio1 bio16 bio17 bio5 bio6 bio7 bio8 
Categorical: biome

x[[1]]@models[[1]]@model
Class     : Maxent 
Reg       : 0.5 
FCs       : lh 
Iterations: 500 
```

**Comment by sgvignali** [comment]
and
```
class(x) == "SDMmodel"
```

**Comment by veroandreo** [comment]
shall I run that? If I do `class(x[[1]])`, I get:
```
[1] "SDMmodelCV"
attr(,"package")
[1] "SDMtune"
```

**Comment by veroandreo** [comment]
```
class(x[[1]])
[1] "SDMmodelCV"
attr(,"package")
[1] "SDMtune"

class(x[[1]]) == "SDMmodel"
[1] FALSE
```

**Comment by sgvignali** [comment]
This is very weird... the `.create_sdmtune_output` function raises the error but when we break the code in pieces the error is not raised... If I cannot recreate the error in my computer it's hard to find out why it happen. 

Do you have any experience with debugging?

**Comment by veroandreo** [comment]
I do not have much experience in debugging, no, but if you tell me what to do, I'm in for it. 

I was just talking to a colleague and he is getting the same error I get. We are both eagerly waiting that the function accepts SDMmodelCV objects.

**Comment by sgvignali** [comment]
It does work, the point is more why it doesn't work in your case. And I really would like to understand why it happens...

To debug the code you should (I assume you are using RStudio):
1. copy the function `.create_sdmtune_output` from GitHub, paste it in a R script file and save it;
2. change the name of the function with my_function
3. source the function
4. execute the function and make sure it raises the error:
```
my_function(list(reduced_var_model, reduced_var_model), metric = "auc",
+                   train_metric = data.frame(x = c(1, 2), y = c(.8, .9)),
+                   val_metric = data.frame(x = c(1, 2), y = c(.6, .8))
                     )
```
5. put a break point at the line I expect the error is raised (`res[i, tunable_hypers[j]] <- slot(m@model, tunable_hypers[j])`). To insert a break point just click on the left of the row number in the script, a red point will appear
6. source the script again and rerun the function
7. the execution of the code should stop at the breaking point
8. in the console execute: `slot(m@model, tunable_hypers[j])`, this should generate the error
9. print `m` and tell me the output please

**Comment by veroandreo** [comment]
I try to follow the instructions, but I don't get the function to work yet.

I copied the function `.create_sdmtune_output` from https://github.com/ConsBiol-unibern/SDMtune/blob/master/R/utils.R into a script, replaced `.create_sdmtune_output` by `my_function` (shall I keep the dot in front of it?) and sourced the content of the file (Source button in RStudio). But when I run the code above, I get: 
```
Error in .get_sdmtune_colnames(metric) : 
  could not find function ".get_sdmtune_colnames"
```
I tried adding `SDMtune:::` in front of .get_sdmtune_colnames, but I get: 
```
 Error: '.get_sdmtune_colnames' is not an exported object from 'namespace:SDMtune' 
```
Is there any missing step(s) in between? Sorry for my ignorance in debugging and thanks for your patience :)

**Comment by sgvignali** [comment]
Let's leave it for the moment. The function works for me in two different computers with two  different settings, is tested in travis and CRAN https://github.com/ConsBiol-unibern/SDMtune/blob/498bea99ed624eb7a8c3602e4697423a2c0b5e62/tests/testthat/test_utils.R#L113

I saw that you have several packages loaded, could you please detach all of them and have only SDMtune loaded?

After run again the code and see if you get the error
```
x <- SDMtune:::.create_sdmtune_output(list(reduced_var_model, reduced_var_model),
                                      metric = "auc",
                                      train_metric = data.frame(x = c(1, 2), y = c(.8, .9)),
                                      val_metric = data.frame(x = c(1, 2), y = c(.6, .8))
                                      ) 
```

**Comment by veroandreo** [comment]
Dear Sergio, 

Yes! Starting from scratch in a session with only `SDMtune`, all goes smoothly! I wonder where is the interference then, i.e., with which package(s). 

Anyway, thanks for your help and patience! :)

**Comment by sgvignali** [comment]
No problem, I am happy that we figured the problem out! And thanks for reporting the problem in GitHub.
I will release a new version in few days, so keep updated.
Best,
Sergio
