### ISSUE TITLE
Error in plotPA: Continuous value supplied to discrete scale

### ISSUE THREAD

**Issue by veroandreo** [ConsBiol-unibern/SDMtune#5]
I'm following the example here: https://consbiol-unibern.github.io/SDMtune/articles/articles/make_predictions.html, but when I try to get the presence-absence plot, I get the following:

```
plotPA(map, th=0.497)
Error: Continuous value supplied to discrete scale
```

I'm using SDMTune 0.2.0

**Comment by sgvignali** [comment]
That's weird... 
How did you create the map object? Could you please print it?

**Comment by veroandreo** [comment]
I'm following the examples in the tutorial, but with my data. Here the commands and objects:

```
map <- predict(default_model_2014_5, data = subset_pred_2014_5_r, type = "cloglog")
thresholds(default_model_2014_5, type = "cloglog")
plotPA(map, th = 0.20)


default_model_2014_5
Object of class SDMmodelCV 
Method: Maxent 

Species: LC 
Replicates: 4 
Presence locations: 25 
Absence locations: 10000 

Model configurations:
--------------------
fc: lqph
reg: 1
iter: 500

Variables:
---------
Continuous: LC08_2014_2015_cva_angle LC08_2014_2015_cva_change_dist_1 LC08_2014_2015_cva_change_dist_2 LC08_2014_2015_cva_change_dist_3 LC08_2014_2015_cva_change_dist_4 LC08_2014_2015_cva_magnitude LC08_20140719_EVI_5_Contr LC08_20140719_EVI_5_Corr LC08_20140719_EVI_5_Entr LC08_20140719_LSWI2_5_Corr LC08_20140719_LSWI2_5_Entr LC08_20140719_LSWI2_average_5 LC08_20140719_NDBI_5_Contr LC08_20140719_NDBI_5_Corr LC08_20140719_NDBI_5_Entr LC08_20140719_NDBI_sd_5 LC08_20140719_NDWI_XU_sd_5 LC08_20140719_tasscap.1_5 LC08_20140719_tasscap.2_5 LC08_20140719_tasscap.4_5 interspersion_20140719_5 richness_20140719_5 
Categorical: LC08_2014_2015_cva_change rf_class_20140719 mode_20140719_5 LC08_2014_2015_cva_change_mode_5


map_2014_5
class      : RasterLayer 
dimensions : 976, 1252, 1221952  (nrow, ncol, ncell)
resolution : 30, 30  (x, y)
extent     : 302040, 339600, 6940230, 6969510  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +south +no_defs +zone=21 +a=6378137 +rf=298.257223563 +towgs84=0.000,0.000,0.000 +to_meter=1 
source     : memory
names      : layer 
values     : 0, 1  (min, max)
```

If I just follow the example with the vitualsp and worldclim, and ony load SDMtune and raster packages, the plotPA() works. But with my data, it does not. I don't understand.

**Comment by sgvignali** [comment]
Thanks, are you sure you are using the version 0.2.0?

The predict function for cross validation is not available in this version. If you try to predict
an SWDmodelCV object you should get the following error message:

Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "SDMmodelCV"
Furthermore, the thresholds function can be used only with SDMmodel objects, see documentation.

The predict method for SDMmodelCV is implemented in the development version and will be released soon (thresholds will be available in the following days).

**Comment by veroandreo** [comment]
Sorry, I didn't say. I'm using the dev version installed with `devtools::install_github("ConsBiol-unibern/SDMtune")` because I saw that predict now also works with SDMmodelCV objects. 

In any case, I tried the `plotPA()` also with a CV model with the data from the example in the tutorials, and it works. It's only with my data that it does not work.

**Comment by sgvignali** [comment]
`plotPA` is a simple function, must be something with your raster.

Could you please try to do 

```
pa <- map >= 0.2
rasterVis::gplot(pa) + ggplot2::geom_tile(ggplot2::aes_(fill = ~value))
```
and also:
```
plot(map)
plot(pa)
```

**Comment by veroandreo** [comment]
All those commands work with no error :)

**Comment by sgvignali** [comment]
and this:
```
rasterVis::gplot(pa) +
  ggplot2::geom_tile(ggplot2::aes_(fill = ~value)) +
  ggplot2::scale_fill_manual(values = c("#67a9cf", "#ef8a62"),
                             breaks = c(1, 0),
                             labels = c("Presence", "Absence"),
                             name = "")
```

**Comment by veroandreo** [comment]
That one gives the error reported originally:
```
Error: Continuous value supplied to discrete scale
```

**Comment by sgvignali** [comment]
It should be fixed now, could you please test it?

Be aware that the function `thresholds` is not yet implemented for CV,
it will be available in few days...

**Comment by veroandreo** [comment]
> It should be fixed now, could you please test it?

Yes, it's working now! Thanks much! I close this one as it is fixed.

> Be aware that the function `thresholds` is not yet implemented for CV,
> it will be available in few days...

+1! Looking forward to it
Thanks again! I like the package a lot!
